# Generated by Django 3.0.1 on 2019-12-27 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.IntegerField(unique=True)),
                ('login', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcaster_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('offline_image_url', models.URLField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('subscriber_count', models.IntegerField(default=0)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('viewable', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=255)),
                ('view_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('video_type', models.CharField(choices=[('upload', 'Upload'), ('archive', 'Archive'), ('highlight', 'Highlight')], max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('twitch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwitchVideo_TwitchUsers', to='Twitch.TwitchUser')),
            ],
        ),
        migrations.CreateModel(
            name='StreamMinuteFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewers', models.IntegerField(default=0)),
                ('live', models.BooleanField(default=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('chatters', models.ManyToManyField(related_name='StreamMinuteFrame_Chatters', to='Twitch.TwitchUser')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StreamMinuteFrame_Games', to='Twitch.Game')),
                ('twitch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StreamMinuteFrame_TwitchUsers', to='Twitch.TwitchUser')),
            ],
        ),
    ]
