# Generated by Django 3.0.1 on 2019-12-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='bot',
            field=models.BooleanField(default=False),
        ),
    ]
