# Generated by Django 3.0.1 on 2019-12-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitch', '0003_auto_20191227_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
