# Generated by Django 3.0.1 on 2019-12-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitch', '0004_twitchuser_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='minutes_watched',
            field=models.IntegerField(default=0),
        ),
    ]
