# Generated by Django 3.0.1 on 2020-01-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitch', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
