# Generated by Django 3.0.1 on 2020-01-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitch', '0008_auto_20200101_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitchuser',
            name='subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchuser',
            name='subscription_months',
            field=models.IntegerField(default=0),
        ),
    ]
