# Generated by Django 3.0.1 on 2020-01-02 07:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitch', '0009_auto_20200102_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchatmessage',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
