# Generated by Django 3.0.1 on 2020-01-02 07:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitch', '0010_twitchchatmessage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
