# Generated by Django 3.0.1 on 2020-01-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitch', '0011_auto_20200102_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField()),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TwitchEvent_FromUsers', to='Twitch.TwitchUser')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TwitchEvent_ToUsers', to='Twitch.TwitchUser')),
            ],
        ),
    ]
