# Generated by Django 3.0.1 on 2020-01-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitch', '0012_followevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followevent',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FollowEvent_FromUsers', to='Twitch.TwitchUser'),
        ),
        migrations.AlterField(
            model_name='followevent',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FollowEvent_ToUsers', to='Twitch.TwitchUser'),
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField()),
                ('cumulative_months', models.IntegerField(blank=True, null=True)),
                ('streak_months', models.IntegerField(blank=True, null=True)),
                ('sub_plan', models.CharField(max_length=5)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubscriptionEvent_FromUsers', to='Twitch.TwitchUser')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubscriptionEvent_ToUsers', to='Twitch.TwitchUser')),
            ],
        ),
    ]
